### ISSUE TITLE
dtkwidget打包失败

### ISSUE THREAD

**Issue by mxdlzg** [rekols/docs#7]
sudo dpkg-buildpackage -b
dpkg-buildpackage: info: source package dtkwidget
dpkg-buildpackage: info: source version 2.0.0-0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Iceyer <me@iceyer.net>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build dtkwidget-master
 debian/rules clean
dh clean --parallel
   dh_testdir -O--parallel
   dh_auto_clean -O--parallel
   dh_clean -O--parallel
 debian/rules build
dh build --parallel
   dh_testdir -O--parallel
   dh_update_autotools_config -O--parallel
   dh_auto_configure -O--parallel
	qmake -makefile -nocache "QMAKE_CFLAGS_RELEASE=-g -O2 " "QMAKE_CFLAGS_DEBUG=-g -O2 " "QMAKE_CXXFLAGS_RELEASE=-g -O2 " "QMAKE_CXXFLAGS_DEBUG=-g -O2 " QMAKE_STRIP=: PREFIX=/usr

process translations/dtkwidget2_am_ET.ts
Updating 'translations/dtkwidget2_am_ET.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ar.ts
Updating 'translations/dtkwidget2_ar.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ast.ts
Updating 'translations/dtkwidget2_ast.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_bg.ts
Updating 'translations/dtkwidget2_bg.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ca.ts
Updating 'translations/dtkwidget2_ca.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_cs.ts
Updating 'translations/dtkwidget2_cs.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_da.ts
Updating 'translations/dtkwidget2_da.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_de.ts
Updating 'translations/dtkwidget2_de.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_el.ts
Updating 'translations/dtkwidget2_el.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_es_419.ts
Updating 'translations/dtkwidget2_es_419.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_es.ts
Updating 'translations/dtkwidget2_es.qm'...
    Generated 30 translation(s) (30 finished and 0 unfinished)

process translations/dtkwidget2_fr.ts
Updating 'translations/dtkwidget2_fr.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_gl_ES.ts
Updating 'translations/dtkwidget2_gl_ES.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_he.ts
Updating 'translations/dtkwidget2_he.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_hr.ts
Updating 'translations/dtkwidget2_hr.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_hu.ts
Updating 'translations/dtkwidget2_hu.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_id.ts
Updating 'translations/dtkwidget2_id.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_it.ts
Updating 'translations/dtkwidget2_it.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ja.ts
Updating 'translations/dtkwidget2_ja.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_lt.ts
Updating 'translations/dtkwidget2_lt.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ms.ts
Updating 'translations/dtkwidget2_ms.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_nl.ts
Updating 'translations/dtkwidget2_nl.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)

process translations/dtkwidget2_pl.ts
Updating 'translations/dtkwidget2_pl.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_pt_BR.ts
Updating 'translations/dtkwidget2_pt_BR.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_pt.ts
Updating 'translations/dtkwidget2_pt.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_ru.ts
Updating 'translations/dtkwidget2_ru.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_sk.ts
Updating 'translations/dtkwidget2_sk.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_sl.ts
Updating 'translations/dtkwidget2_sl.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_sr.ts
Updating 'translations/dtkwidget2_sr.qm'...
    Generated 1 translation(s) (1 finished and 0 unfinished)
    Ignored 12 untranslated source text(s)

process translations/dtkwidget2_tr.ts
Updating 'translations/dtkwidget2_tr.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2.ts
Updating 'translations/dtkwidget2.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 30 untranslated source text(s)

process translations/dtkwidget2_uk.ts
Updating 'translations/dtkwidget2_uk.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)

process translations/dtkwidget2_zh_CN.ts
Updating 'translations/dtkwidget2_zh_CN.qm'...
    Generated 30 translation(s) (30 finished and 0 unfinished)

process translations/dtkwidget2_zh_TW.ts
Updating 'translations/dtkwidget2_zh_TW.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
   dh_auto_build -O--parallel
	make -j8
make[1]: Entering directory '/home/mxdlzg/Downloads/Qt/dtkwidget-master'
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mxdlzg/Downloads/Qt/dtkwidget-master/src/src.pro -nocache 'QMAKE_CFLAGS_RELEASE=-g -O2 ' 'QMAKE_CFLAGS_DEBUG=-g -O2 ' 'QMAKE_CXXFLAGS_RELEASE=-g -O2 ' 'QMAKE_CXXFLAGS_DEBUG=-g -O2 ' QMAKE_STRIP=: PREFIX=/usr -o Makefile ) && make -f Makefile 
Project MESSAGE: build dtk with version 2.0.7.7
Info: creating cache file /home/mxdlzg/Downloads/Qt/dtkwidget-master/src/.qmake.cache
Checking for libdframeworkdbus... no
Project MESSAGE: config cmake module: DtkWidget
Project MESSAGE: write cmake file to /home/mxdlzg/Downloads/Qt/dtkwidget-master/src/../cmake/DtkWidget//DtkWidgetConfig.cmake
Project ERROR: includes.path must not empty, please load(dtk_build) first!
Makefile:44: recipe for target 'sub-src-make_first-ordered' failed
make[1]: *** [sub-src-make_first-ordered] Error 3
make[1]: Leaving directory '/home/mxdlzg/Downloads/Qt/dtkwidget-master'
dh_auto_build: make -j8 returned exit code 2
debian/rules:21: recipe for target 'build' failed
make: *** [build] Error 25
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by rekols** [comment]
emmmm

**Comment by rekols** [comment]
还有依赖没装：libdframeworkdbus-dev

用 dpkgbuild-package 的时候应该有提示的。
